<a href="https://colab.research.google.com/github/megamindavi/pytorch_training/blob/main/linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')


In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.4646, -0.5477, -0.1247],
        [ 0.1722,  1.0970, -2.1076]], requires_grad=True)
tensor([-0.0089,  1.9858], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -75.9836,   -2.5664],
        [ -98.4672,  -20.6876],
        [-121.0560,   41.7325],
        [ -75.5628,  -11.2557],
        [ -93.3764,  -28.3453]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [13]:
# Compute loss
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(144.1458, grad_fn=<SqrtBackward0>)


In [14]:
# Compute gradients
loss.backward()

In [15]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.4646, -0.5477, -0.1247],
        [ 0.1722,  1.0970, -2.1076]], requires_grad=True)
tensor([[-14070.5137, -15970.1709,  -9688.1230],
        [ -7880.0210,  -8804.0898,  -5660.3022]])


In [16]:
w
w.grad

tensor([[-14070.5137, -15970.1709,  -9688.1230],
        [ -7880.0210,  -8804.0898,  -5660.3022]])

In [17]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [19]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(144.1458, grad_fn=<SqrtBackward0>)


In [20]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [21]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-50.8445,  11.5196],
        [-65.4072,  -2.1456],
        [-81.7938,  63.6695],
        [-50.7574,   2.6629],
        [-61.5530, -10.4930]], grad_fn=<AddBackward0>)


In [23]:
# Calculate the loss
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(119.3120, grad_fn=<SqrtBackward0>)


In [24]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-11473.4355, -13174.8887,  -7964.2305],
        [ -6424.8936,  -7238.6211,  -4694.4248]])
tensor([-138.2712,  -78.9573])


In [25]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [26]:
print(w)
print(b)

tensor([[-0.2091, -0.2563,  0.0518],
        [ 0.3153,  1.2575, -2.0040]], requires_grad=True)
tensor([-0.0059,  1.9876], requires_grad=True)


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(99.1202, grad_fn=<SqrtBackward0>)


In [42]:
# Train for 100 epochs
for i in range(10000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [43]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(0.7529, grad_fn=<SqrtBackward0>)


In [44]:
preds

tensor([[ 57.1642,  70.6435],
        [ 82.2075, 100.4601],
        [118.6933, 132.9048],
        [ 21.0815,  36.9733],
        [101.9203, 119.1908]], grad_fn=<AddBackward0>)

In [45]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])