<a href="https://colab.research.google.com/github/megamindavi/pytorch_training/blob/main/linear_regression_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:

# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')


In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.4646, -0.5477, -0.1247],
        [ 0.1722,  1.0970, -2.1076]], requires_grad=True)
tensor([-0.0089,  1.9858], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -75.9836,   -2.5664],
        [ -98.4672,  -20.6876],
        [-121.0560,   41.7325],
        [ -75.5628,  -11.2557],
        [ -93.3764,  -28.3453]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [13]:
# Compute loss
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(144.1458, grad_fn=<SqrtBackward0>)


In [14]:
# Compute gradients
loss.backward()

In [15]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.4646, -0.5477, -0.1247],
        [ 0.1722,  1.0970, -2.1076]], requires_grad=True)
tensor([[-14070.5137, -15970.1709,  -9688.1230],
        [ -7880.0210,  -8804.0898,  -5660.3022]])


In [16]:
w
w.grad

tensor([[-14070.5137, -15970.1709,  -9688.1230],
        [ -7880.0210,  -8804.0898,  -5660.3022]])

In [17]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [19]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(144.1458, grad_fn=<SqrtBackward0>)


In [20]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [21]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-50.8445,  11.5196],
        [-65.4072,  -2.1456],
        [-81.7938,  63.6695],
        [-50.7574,   2.6629],
        [-61.5530, -10.4930]], grad_fn=<AddBackward0>)


In [23]:
# Calculate the loss
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(119.3120, grad_fn=<SqrtBackward0>)


In [24]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-11473.4355, -13174.8887,  -7964.2305],
        [ -6424.8936,  -7238.6211,  -4694.4248]])
tensor([-138.2712,  -78.9573])


In [25]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [26]:
print(w)
print(b)

tensor([[-0.2091, -0.2563,  0.0518],
        [ 0.3153,  1.2575, -2.0040]], requires_grad=True)
tensor([-0.0059,  1.9876], requires_grad=True)


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(99.1202, grad_fn=<SqrtBackward0>)


In [42]:
# Train for 100 epochs
for i in range(10000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [43]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(torch.sqrt(loss))

tensor(0.7529, grad_fn=<SqrtBackward0>)


In [44]:
preds

tensor([[ 57.1642,  70.6435],
        [ 82.2075, 100.4601],
        [118.6933, 132.9048],
        [ 21.0815,  36.9733],
        [101.9203, 119.1908]], grad_fn=<AddBackward0>)

In [45]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [46]:
import torch.nn as nn

In [47]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [48]:
inputs


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [49]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [50]:
from torch.utils.data import TensorDataset

In [51]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [52]:
from torch.utils.data import DataLoader

In [53]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [55]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    #break

tensor([[103.,  43.,  36.],
        [102.,  43.,  37.],
        [101.,  44.,  37.],
        [ 74.,  66.,  43.],
        [ 92.,  87.,  64.]])
tensor([[ 20.,  38.],
        [ 22.,  37.],
        [ 21.,  38.],
        [ 57.,  69.],
        [ 82., 100.]])
tensor([[ 91.,  87.,  65.],
        [ 73.,  66.,  44.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 80., 102.],
        [ 57.,  69.],
        [103., 119.],
        [ 81., 101.],
        [119., 133.]])
tensor([[ 68.,  97.,  70.],
        [ 68.,  96.,  71.],
        [ 88., 134.,  59.],
        [ 87., 135.,  57.],
        [ 73.,  67.,  43.]])
tensor([[102., 120.],
        [104., 118.],
        [118., 132.],
        [118., 134.],
        [ 56.,  70.]])


In [56]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.3147,  0.5702, -0.2407],
        [ 0.5180,  0.1419, -0.1253]], requires_grad=True)
Parameter containing:
tensor([0.4928, 0.3637], requires_grad=True)


In [58]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.3147,  0.5702, -0.2407],
         [ 0.5180,  0.1419, -0.1253]], requires_grad=True),
 Parameter containing:
 tensor([0.4928, 0.3637], requires_grad=True)]

In [59]:
# Generate predictions
preds = model(inputs)
preds

tensor([[  5.3709,  42.2996],
        [  6.6250,  51.9725],
        [ 35.5572,  57.1803],
        [-15.9959,  54.6691],
        [ 16.6658,  40.9587],
        [  4.4860,  42.6758],
        [  5.8141,  51.7052],
        [ 35.0017,  57.5730],
        [-15.1110,  54.2930],
        [ 16.7398,  40.3153],
        [  4.5600,  42.0324],
        [  5.7401,  52.3486],
        [ 36.3681,  57.4476],
        [-16.0699,  55.3125],
        [ 17.5507,  40.5826]], grad_fn=<AddmmBackward0>)

In [60]:
# Import nn.functional
import torch.nn.functional as F

In [61]:
# Define loss function
loss_fn = F.mse_loss

In [63]:
loss = loss_fn(model(inputs), targets)
print(torch.sqrt(loss))

tensor(62.5926, grad_fn=<SqrtBackward0>)


In [64]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [65]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [69]:
fit(1000, model, loss_fn, opt, train_dl)


Epoch [10/1000], Loss: 53.5947
Epoch [20/1000], Loss: 37.2827
Epoch [30/1000], Loss: 40.1153
Epoch [40/1000], Loss: 26.3341
Epoch [50/1000], Loss: 27.5299
Epoch [60/1000], Loss: 25.5078
Epoch [70/1000], Loss: 17.5587
Epoch [80/1000], Loss: 17.9762
Epoch [90/1000], Loss: 19.9538
Epoch [100/1000], Loss: 29.5246
Epoch [110/1000], Loss: 22.2506
Epoch [120/1000], Loss: 29.9483
Epoch [130/1000], Loss: 23.6982
Epoch [140/1000], Loss: 21.1474
Epoch [150/1000], Loss: 11.0166
Epoch [160/1000], Loss: 7.7461
Epoch [170/1000], Loss: 7.2218
Epoch [180/1000], Loss: 9.9226
Epoch [190/1000], Loss: 13.3178
Epoch [200/1000], Loss: 10.8921
Epoch [210/1000], Loss: 14.0823
Epoch [220/1000], Loss: 6.7807
Epoch [230/1000], Loss: 8.2183
Epoch [240/1000], Loss: 6.4235
Epoch [250/1000], Loss: 9.2377
Epoch [260/1000], Loss: 5.7739
Epoch [270/1000], Loss: 6.4506
Epoch [280/1000], Loss: 9.0097
Epoch [290/1000], Loss: 6.2815
Epoch [300/1000], Loss: 7.8898
Epoch [310/1000], Loss: 1.9269
Epoch [320/1000], Loss: 8.5213

In [70]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.0866,  70.4766],
        [ 81.8319, 100.2819],
        [118.6255, 133.2257],
        [ 20.9401,  37.8625],
        [101.5247, 118.0645],
        [ 55.8320,  69.3909],
        [ 81.6503, 100.3360],
        [118.8941, 133.8012],
        [ 22.1948,  38.9482],
        [102.5977, 119.2044],
        [ 56.9049,  70.5308],
        [ 80.5773,  99.1962],
        [118.8072, 133.1715],
        [ 19.8672,  36.7226],
        [102.7793, 119.1502]], grad_fn=<AddmmBackward0>)

In [71]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])