In [ ]:
import torch

In [ ]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
t3.shape

torch.Size([3, 2])

In [ ]:
t4.shape

torch.Size([2, 2, 3])

In [ ]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y= w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward()

In [ ]:

x.grad
b.grad

tensor(1.)

In [ ]:
w.grad

tensor(3.)

In [ ]:
import numpy as np


x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [ ]:
z= y.numpy()
z

array([[1., 2.],
       [3., 4.]])